version: '3.8'

services:
  # 1. O Banco de Dados MongoDB
  mongodb:
    image: mongo:4.4.29
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. O Back-end em Flask
  backend:
    image: marciobrener98/task-backend:latest
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  # 3. O Front-end com Bootstrap
  frontend:
    image: marciobrener98/task-frontend:latest
    restart: always
    ports:
      - "80:80" # Ajuste a porta interna do seu frontend se não for 80

volumes:
  mongo_data: