version: '3.8'

services:
  # 1. Banco de Dados MongoDB
  mongodb:
    image: mongo:4.4.29
    volumes:
      - mongo_data:/data/db
    networks:
      - task_network
    deploy:
      restart_policy:
        condition: on-failure

  # 2. O Back-end em Flask
  backend:
    image: marciobrener98/taskmanager-back:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    networks:
      - task_network
    depends_on:
      - mongodb
    deploy:
      restart_policy:
        condition: on-failure

  # 3. O Front-end com Bootstrap
  frontend:
    image: marciobrener98/taskmanager-front:latest
    ports:
      - "80:80"
    networks:
      - task_network
    depends_on:
      - backend
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  mongo_data:

networks:
  task_network:
    driver: overlay # O driver overlay é o padrão e obrigatório para comunicação entre nós no Swarm